package tests

var Port = 7540
var DBFile = "../scheduler.db"
var FullNextDate = true
var Search = true
var Token = `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjI5NDgyODIsImhhc2giOlsxMTYsNCw3MiwxOTQsMjE5LDc4LDM2LDE4Miw2MCw0OCwxNDQsMjMwLDkxLDI1MywyNTEsMjA3LDIzMiwxMTIsMjAzLDU5LDIyMCw2MSwxNjIsMTA1LDEyOSw0OCwxMTAsMjU1LDIyMSw4LDYsMjJdfQ.woMMkoR_dHMWwwVTSQCTCxLB4sqUQnEGyzbV_A1S5fE`
